### ISSUE TITLE
How does one flash the firmware onto the board?

### ISSUE THREAD

**Issue by freaker2112** [Nitrokey/nitrokey-fido-u2f-firmware#16]
Stupid question, I know. I needed a USB-C version of this, so I built one. But I cant figure out how to flash the firmware onto it. I assume the debug pins are used.

**Comment by szszszsz** [comment]
Hey! I've heard there are no stupid questions :-)

You need a Silicon Labs USB Debug Adapter, and connect/solder D+, D- and GND wires to the hardware.
Then you need a proper IDE to build and flash the firmware using the debug adapter.
I have not done this for a long time, so I can't help much more, but I am sure you should be able to find more information regarding this on the proper hardware forums.

**Comment by szszszsz** [comment]
Bonus picture with my dusty hard-wired setup:
[20230524_183925](https://github.com/Nitrokey/nitrokey-fido-u2f-firmware/assets/17005426/e4bdf0ba-cb67-496a-8610-5737f92d9e65)

Best of luck!
